name: flutter_mailer
description: Share an email to device Email - Client supports multiple Attachments
version: 3.0.1
homepage:  https://github.com/taljacobson/flutter_mailer

dependencies:
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_test:
    sdk: flutter
  image_picker:
    git: https://github.com/kumsumit/image_picker.git
  path_provider:
    git: https://github.com/kumsumit/path_provider.git
  flutter_lints: ^6.0.0  
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.dataxad.flutter_mailer
        pluginClass: FlutterMailerPlugin
      ios:
        pluginClass: FlutterMailerPlugin

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: ">=3.32.0"
